// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_kuzKwpJqte9zbhfBP5M9rq6qAYUn-G8',
    appId: '1:773386721810:web:59e0603f5e3300154416cb',
    messagingSenderId: '773386721810',
    projectId: 'hrt-kozanis',
    authDomain: 'hrt-kozanis.firebaseapp.com',
    storageBucket: 'hrt-kozanis.appspot.com',
    measurementId: 'G-Y21P9T78TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWg79-84_1ax5t44e7Mx0tJJDqCE4QNbs',
    appId: '1:773386721810:android:e223d16e675fc69f4416cb',
    messagingSenderId: '773386721810',
    projectId: 'hrt-kozanis',
    storageBucket: 'hrt-kozanis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClFXz-7uy_s1jYOMXarUfQxIIR9FOL2H8',
    appId: '1:773386721810:ios:ccb6b1d4958b4b5e4416cb',
    messagingSenderId: '773386721810',
    projectId: 'hrt-kozanis',
    storageBucket: 'hrt-kozanis.appspot.com',
    androidClientId: '773386721810-2boui5bqcd9dducb3c511r4nbn7u05qn.apps.googleusercontent.com',
    iosClientId: '773386721810-42koo3p3h3viv43peqltl62dhcp8iil5.apps.googleusercontent.com',
    iosBundleId: 'com.example.hrtKozanis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClFXz-7uy_s1jYOMXarUfQxIIR9FOL2H8',
    appId: '1:773386721810:ios:47f3c03628c0f35d4416cb',
    messagingSenderId: '773386721810',
    projectId: 'hrt-kozanis',
    storageBucket: 'hrt-kozanis.appspot.com',
    androidClientId: '773386721810-2boui5bqcd9dducb3c511r4nbn7u05qn.apps.googleusercontent.com',
    iosClientId: '773386721810-m31fqid88pik46qivq0k8v9eekig3q81.apps.googleusercontent.com',
    iosBundleId: 'com.example.hrtKozanis.RunnerTests',
  );
}
